import operator
from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class TaskStatus(StrEnum):
    """Enumeration of the task lifecycle states."""

    PENDING = "pending"
    RESEARCHING = "researching"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"  # Task was skipped due to no search results


class TodoItem(BaseModel):
    """
    Represents a single research task unit decomposed from the main topic.
    This serves as the atomic work unit for the Agent.
    """

    id: int = Field(..., title="Task ID", description="Unique sequence number identifying the research order.")

    title: str = Field(
        ..., title="Title", description="A short, descriptive name for the sub-task (e.g., 'SpaceX Founding History')."
    )

    intent: str = Field(
        ..., title="Intent", description="Explains why this task is being performed and the specific goals to achieve."
    )

    query: str = Field(
        ...,
        title="Search Query",
        description="Search-engine optimized keywords or phrases to retrieve the most relevant results.",
    )

    status: TaskStatus = Field(
        default=TaskStatus.PENDING, title="Status", description="The current execution progress of the task."
    )

    summary: str | None = Field(
        default=None,
        title="Summary",
        description="The synthesized findings generated by the Agent after analyzing search results.",
    )

    sources_summary: str | None = Field(
        default=None,
        title="Sources Summary",
        description="A brief overview or list of primary URLs and sources cited for this task.",
    )

    notices: list[str] = Field(
        default_factory=list,
        title="Notices",
        description="Special notes, warnings, or error messages encountered during research.",
    )

    review_notes: str | None = Field(
        default=None,
        title="Reviewer Notes",
        description="Optional reflection / critique generated by a reviewer agent before summarization.",
    )

    stream_token: str | None = Field(
        default=None,
        title="Stream Token",
        description="Used for SSE communication to identify the active task being streamed to the frontend.",
    )

    model_config = ConfigDict(use_enum_values=True, str_strip_whitespace=True)


class SummaryState(BaseModel):
    """
    The global state of the research workflow.
    This stores all gathered information and the current progress.
    """

    research_topic: str | None = Field(
        default=None, title="Research Topic", description="The main topic or question provided by the user."
    )

    web_research_results: Annotated[list[str], operator.add] = Field(
        default_factory=list,
        title="Web Research Results",
        description="A cumulative list of formatted search context strings gathered across all loops.",
    )

    sources_gathered: Annotated[list[str], operator.add] = Field(
        default_factory=list, title="Sources Gathered", description="A cumulative list of all URLs visited and cited."
    )

    research_loop_count: int = Field(
        default=0, title="Research Loop Count", description="The current iteration number of the research cycle."
    )

    running_summary: str | None = Field(
        default=None, title="Running Summary", description="A legacy field for storing intermediate summary text."
    )

    todo_items: Annotated[list[TodoItem], operator.add] = Field(
        default_factory=list,
        title="Todo Items",
        description="The list of sub-tasks. New tasks are appended to this list.",
    )

    structured_report: str | None = Field(
        default=None, title="Structured Report", description="The final synthesized Markdown report."
    )

    model_config = ConfigDict(arbitrary_types_allowed=True)


class SummaryStateInput(BaseModel):
    """
    The input schema for the research workflow.
    Only the topic is required from the user.
    """

    research_topic: str = Field(..., title="Research Topic", description="The main subject the user wants to research.")


class SummaryStateOutput(BaseModel):
    """
    The output schema for the research workflow.
    This is what the frontend or the user will receive.
    """

    running_summary: str | None = Field(
        default=None,
        title="Running Summary",
        description="The latest intermediate summary text (for backward compatibility).",
    )

    report_markdown: str | None = Field(
        default=None, title="Report Markdown", description="The final synthesized report in Markdown format."
    )

    todo_items: list[TodoItem] = Field(
        default_factory=list, title="Todo Items", description="The list of tasks and their individual research results."
    )

    usage: dict[str, int] = Field(
        default_factory=dict,
        title="Token Usage",
        description="Aggregate LLM token consumption for the entire pipeline run.",
    )


class TaskReview(BaseModel):
    """Structured rubric-style review output for a single task."""

    coverage_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="How completely the context covers the task intent (0–1).",
    )
    reliability_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Perceived reliability/quality of the evidence (0–1).",
    )
    clarity_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="How clear and non-contradictory the context is (0–1).",
    )
    overall_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Overall assessment combining the above dimensions (0–1).",
    )
    should_reresearch: bool = Field(
        ...,
        description="Whether another search iteration should be run for this task.",
    )
    recommendations: list[str] = Field(
        default_factory=list,
        description="Concrete suggestions for improving coverage or reliability (may be used to refine queries).",
    )
    notes: str = Field(
        default="",
        description="Free-form natural language explanation of the review.",
    )
